### ISSUE TITLE
enable segment time comparison settings keep getting re-enabled

### ISSUE THREAD

**Issue by hmoffatt** [thomaschampagne/stravistix#204]
Every time Stravistix gets updated, the four "enable segment time comparison" settings for cycling seem to get re-enabled. I like them off because I don't like the flickering as they are loaded dynamically.

**Comment by thomaschampagne** [comment]
@hmoffatt Yes it's normal at the moment.

It-s auto re-enabled because it was disabled in the past (bugs and low
performance). I wanted to make sure people were able to see changes of the
feature from last updates.

You can get them off right now, they will not be re-enable in future.

Tom

On Thu, Mar 10, 2016 at 8:48 AM hmoffatt <notifications@github.com> wrote:

> Every time Stravistix gets updated, the four "enable segment time
> comparison" settings for cycling seem to get re-enabled. I like them off
> because I don't like the flickering as they are loaded dynamically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thomaschampagne/stravistix/issues/204>.
>
-- 
Thomas Champagne

**Comment by hmoffatt** [comment]
And now they're back again.

**Comment by thomaschampagne** [comment]
Strange.. Because i disabled them from people comming from 3.2.0 & 3.2.1

@see https://github.com/thomaschampagne/stravistix/blob/master/hook/extension/js/background.js#L45

Maybe you came from version under 3.2.0 on another browser from another computer?!

In all case this the "re enable" will be deleted on the next version (function enableSegmentTimeComparisonFeature will be deleted).

I just wanted people who disabled that before should be able to see changes on the feature...

Thanks for feedback,

Tom
