### ISSUE TITLE
Javascript error on profile page

### ISSUE THREAD

**Issue by yblondeau** [thomaschampagne/stravistix#292]
A Javascript error is raised on my profile page on [this line](https://github.com/thomaschampagne/stravistix/blob/develop/hook/extension/js/modifiers/AthleteStatsModifier.ts#L142): `AthleteStatsModifier.js:101 Uncaught TypeError: Cannot read property 'sort' of undefined`

As my profiles contains no rides but runs only, for all activities of [this loop](https://github.com/thomaschampagne/stravistix/blob/develop/hook/extension/js/modifiers/AthleteStatsModifier.ts#L103) the value of `activity.t` is `1` and thus the first cell of the `types` array is `undefined`.

As a consequence the "year progression" part is never displayed.

Thanks for the good work!

**Comment by thomaschampagne** [comment]
Thanks for report. Same problem than reported here: 

https://github.com/thomaschampagne/stravistix/issues/289

Thanks for the case given and analysis.

**Comment by yblondeau** [comment]
Hi Thomas!

You're right, it seems to be the same case. This athlete has also no ride on his profile which should cause the same error.

**Comment by thomaschampagne** [comment]
Is the problem fixed with this build and with consistent results? [stravistix_build_test](https://github.com/thomaschampagne/stravistix/files/536324/stravistix_v4.3.2_2016-10-18_13.15.47.zip)

**How to install standalone build:** https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

Thanks for your help :)

**Comment by yblondeau** [comment]
Hi Thomas,
Yes, the issue is fixed with your test build! Great job!
Thanks !

**Comment by thomaschampagne** [comment]
Thanks ! Soon released ;)
