### ISSUE TITLE
Watts / KG Calculation

### ISSUE THREAD

**Issue by sheywood** [thomaschampagne/stravistix#308]
**Bug description:** 
The Watts per KG metric isn't being calculated correctly. For example, you can view my ride details at https://www.strava.com/activities/792557891.  I weigh 295lbs (133 KG) and produced about 220 Watts during my ride. You can see both values in the attached screenshot. My Watts per KG should be roughly 1.65. Instead, your service is reporting 2.76

**Actual Behavior:** 
Reporting 2.76 watts/kg
**Expected Behavior:** 
Should report 1.65 watts/kg
**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
Version 54.0.2840.98 (64-bit)

**Plugin version:** 
5.0.0
**Activities links?:** 
https://www.strava.com/activities/792557891
**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**
<img width="896" alt="screen shot 2016-12-05 at 10 09 18 pm" src="https://cloud.githubusercontent.com/assets/97638/20914934/a5ca7594-bb37-11e6-88f2-8c9ec9b79c2f.png">
<img width="812" alt="screen shot 2016-12-05 at 10 09 37 pm" src="https://cloud.githubusercontent.com/assets/97638/20914935/a5daf4e6-bb37-11e6-882a-4f8275aaad5a.png">

**Comment by thomaschampagne** [comment]
@sheywood Thanks for you report.

It's probably due to the weight which must be configured now from STX Athlete Settings:

Go to your athelete settings and set your weight. 
[chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/index.html#/athleteSettings](chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/index.html#/athleteSettings)

Like hr min/max, this value will be synced between your chrome browsers (with your google account).

Settings weight is mandatory for mass activites processing in synchronisation (fitness trend use it)

I didn't communicate as well around... i will..

Let me know if your problem is fixed. It should

Tom
