### ISSUE TITLE
The elapsed (total) moving time should be used to calculate TRIMP

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#330]

**Comment by benzonico** [comment]
Hi @thomaschampagne !
First, stravistix is really cool and trimp score is an awesome feature. Thanks for the good work.

I want to highlight to you a case where this trimp computation on elapsed time rather than moving time is actually not ideal. 
This activity for instance is just an aggregation of two commute : one at lunch and one after work.
https://www.strava.com/activities/867717279/analysis

So what I did in this case is that I started the activity with cardio on (forgot to turn it off after run). Then biked to work. And 4 hours later, leave work and resume the activity. 

So for trimp based on elapsed time I biked 5hours at ~130bpm whereas in reality I only did about 22minutes. (And so I have a huge peak of fatigue which is wrong). 

Hope that can help to refine this computation. let me know if you prefer that I open a dedicated issue.

**Comment by thomaschampagne** [comment]
Trimp must not take care of moving. For sports which have not movements. Problem is from strava which hold hr value during paused state...

![image](https://cloud.githubusercontent.com/assets/151973/23061618/e3397830-f502-11e6-95ea-42c5816a6604.png)

**Comment by thomaschampagne** [comment]
I will try to detect this from code.

**Comment by thomaschampagne** [comment]
@benzonico Hey you can test a zip build here: 
https://ci.appveyor.com/project/thomaschampagne/stravistix/build/artifacts

Install steps: https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

Tom

**Comment by thomaschampagne** [comment]
Hi @benzonico Is your problem fixed?

Regards,

Tom ;)

**Comment by benzonico** [comment]
Hi @thomaschampagne, sorry for the delay of answer but it seems to be fixed ! Same kind of activity today and trimp did not went through the roof ! nice work !
