### ISSUE TITLE
Issue with Enabling Swim

### ISSUE THREAD

**Issue by sdakuri** [thomaschampagne/stravistix#354]
**Bug description:** 
Enabling the Swim, messes up the whole stats, numbers and chart.

**Actual Behavior:** 
With Swim enabled, the plugin show's my fitness numbers as 12514.3, fatigue numbers as 34766.9
**Expected Behavior:** 
With Swim disabled, the plugin shows my fitness numbers 72.1 and fatigue numbers as 126.8. So obviously something is off. My swim FTP is 40 meters per min. 
**Steps to Reproduce:** 
- Added Swim FTP as 40 meters per second.
 - Enable Swim 

**Chrome version** 
Version 56.0.2924.87 (64-bit)

**Plugin version:** 
5.6.1
**Activities links?:** 
https://www.strava.com/athletes/56588
**Console errors? (press F12 to see developer console, and copy paste here):** 
No
``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

<img width="1079" alt="screen shot 2017-03-12 at 9 02 39 pm" src="https://cloud.githubusercontent.com/assets/1792020/23841205/e3d0139e-0768-11e7-8482-5a4756167a1b.png">
<img width="1091" alt="screen shot 2017-03-12 at 9 03 25 pm" src="https://cloud.githubusercontent.com/assets/1792020/23841206/e3d2b2ca-0768-11e7-9c7a-84cd4292b8e3.png">

**Comment by thomaschampagne** [comment]
Thanks for report :)

Do you have a backup of your history to put here to debug on my side?

(From the clock icon > backup)

Thanks

**Comment by sdakuri** [comment]
Here you go. Thanks for all the awesome work.

[2017.3.14-9.34_v5.6.1.history.json.zip](https://github.com/thomaschampagne/stravistix/files/842033/2017.3.14-9.34_v5.6.1.history.json.zip)

**Comment by thomaschampagne** [comment]
Thanks @sdakuri 

I loaded your file.

Graph is correct from my side. The problem is comming from some of your activites where you have impossible paces: some can hit 8s / 100m :). (World record on 100m by César Cielo is 46.91s ^^)

And swim scores are consequently crazy: over 300 000 sometime... 

**Examples:**

https://www.strava.com/activities/646695549
https://www.strava.com/activities/646695541
https://www.strava.com/activities/646659590
https://www.strava.com/activities/655970724
...

```json
    {
      "id": 655970724,
      "bike_id": null,
      "calories": null,
      "commute": false,
      "display_type": "Swim",
=>    "distance_raw": 1280.2,
      "elapsed_time_raw": 2749,
      "elevation_gain_raw": 0,
      "elevation_unit": "ft",
      "hasPowerMeter": false,
=>    "moving_time_raw": 137, 
      "name": "Evening Swim",
      "private": false,
      "short_unit": "yd",
      "start_time": "2016-07-28T01:05:55+0000",
      "trainer": true,
      "type": "Swim"
    },
```
1280.2 meters performed in 137 seconds only (~9m/s). Fast swim :)

What says your Garmin fēnix 2 data on garmin connect? Same impossible paces?

If they are correct try to delete strange swim activities from strava and re upload them from garmin to strava... or maybe try with https://tapiriik.com/ to bulk upload

let me know

**Comment by thomaschampagne** [comment]
@sdakuri Any updates? ty :)

**Comment by thomaschampagne** [comment]
@sdakuri I lauche release 5.7.0.

Let me know btw,

Tom

**Comment by sdakuri** [comment]
Hey Tom,

Sorry was not able to get to this earlier. Garmin Connect actually lists them right. 

Ex one of the activities you had listed in the comment above - https://connect.garmin.com/modern/activity/1222341319

**Comment by sdakuri** [comment]
I did go back and delete all those "fast" 🏊 's :D

**Comment by thomaschampagne** [comment]
Tell me if your problem is well fixed after reupload ;)
