### ISSUE TITLE
Year progressions crash

### ISSUE THREAD

**Issue by Djaouws** [thomaschampagne/stravistix#511]
Year progression never loads, after a while aprox. 30 sec the plugin crach and i must reactivate it.
I have the plugin on a another coputer but it the same issue.

I have Google Chrome Version 64.0.3282.119 (Officiell version) (64 bitar)

**Comment by thomaschampagne** [comment]
Hi @Djaouws .

This feature is completly redone if the next app. I will concentrate my work on. Can you test this with the new app in Open Beta? here: https://www.strava.com/clubs/242874/posts/1333144

Let me know if it works or not. If not i will dive in for the new app.

**Comment by Djaouws** [comment]
Hi Thomas.
When i have done a full sync and then choose Fitness trend or Year progressison the plugin crach/freezes.
So the result for me is that it does not work, sorry.

I roll back to version 5.13.0 Stable

I have only tested it on one copmuter with Google Chrome Version 64.0.3282.119

**Comment by thomaschampagne** [comment]
Could you export me your stravistix history (.json file) so i can debug that?

**Comment by Djaouws** [comment]
Hi 
I sent you a bug report thru google docs "StravistiX Open Beta - Bugs Tracking"

**Comment by thomaschampagne** [comment]
@Djaouws Found your problem !

You have an activity that have corrupted date... this one: https://www.strava.com/activities/693704976

Year is 0001 instead of 2014, 2015, ...

Basically it works but... Code enter in a strong big loop to find any activities from each day from 0001/01/01 to today (2018/02/15). Not sure you was born on year zero ;)

Change the date of this activity.. Edit from strava? Or delete then re-upload properly.

Next... redo a FULL sync from stravistix and you're done ;)

Tom

**Comment by Djaouws** [comment]
Thank you very much!
