### ISSUE TITLE
No stress score without HR

### ISSUE THREAD

**Issue by Neo121183** [thomaschampagne/stravistix#632]
I thought this got implimented?
I went for a little ride today, but it shows as no stress score still when I dont use HR atleast.

**Comment by prdubois** [comment]
+1 on this. Sometimes it works, sometimes it doesn't. I never managed to make it work with my gf Strava account. Here's a screenshot showing that the Estimations are properly enabled no stress score for a ride without HR:
![image](https://user-images.githubusercontent.com/8712266/43204977-4b17cb94-8ff0-11e8-9625-3fdc18e93680.png)
A cycling FTP value is set and a full resync of the activities has been done.

**Comment by thomaschampagne** [comment]
@Neo121183 @prdubois Sry for delay of reply

Does rides has estimated power data given by strava? (Estimated power average strava stats should be sufficient to verify this. ) If not make sure you set your weight in strava settings because strava needs it to estimated the power stream of an activity. Only future rides will have power stream estimated

You may also clear and resync your history because some activities have to be recalculated with the new update

**Comment by Neo121183** [comment]
Sorry. Seems it was my fault.
Dident see the setting to activate it.
Thought it was automatic.

Den ons. 8. aug. 2018, 16:42 skrev Thomas Champagne <
notifications@github.com>:

**Comment by prdubois** [comment]
Thanks Thomas. Indeed weight was not set on my girlfriend's Strava profile. That explains it. So unfortunately only future rides will have an estimated stress score then?

**Comment by thomaschampagne** [comment]
@prdubois Yes only future rides. You can still export your history from strava (archive of gpx files) => Delete strava activities and re-upload to strava from gpx files exported.. :/

**Comment by prdubois** [comment]
Hmmm, but then she would lose all the kudos and comments. Perhaps I could create a fake Strava profile just to get an up-to-date fitness trend curve from Stravistix but that seems a lot of work. She's in the final two weeks before her big race for which she's been training all summer so I was curious to see where she is in terms of form but oh well, At least now everything is in place to track next season.

Thanks for your help!
